### ISSUE TITLE
Unable to load DLL 'Microsoft.WITDataStore32.dll'

### ISSUE THREAD

**Issue by eliassal** [ALM-Rangers/Extracting-effective-permissions-from-TFS#11]
Hi, just downloaded, compiled the program PermissionsExtractionTool.exe, getting the following error:

===== Extracting Permissions for User salam\salam ======

**Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'Microsoft.WITDataStore32.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)**
   at Microsoft.TeamFoundation.WorkItemTracking.Client.DataStore.DataStoreNative32.CreateDatastore(IntPtr& handle)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.DataStore.DataStoreNative.CreateDatastore(IntPtr& handle)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemStore.InitializeInternal()
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemStore.Microsoft.TeamFoundation.Client.ITfsTeamProjectCollectionObject.Initialize(TfsTeamProjectCollection teamProjectCollection)
   at Microsoft.TeamFoundation.Client.TfsTeamProjectCollection.InitializeTeamFoundationObject(String fullName, Object instance)
   at Microsoft.TeamFoundation.Client.TfsConnection.CreateServiceInstance(Assembly assembly, String fullName)
   at Microsoft.TeamFoundation.Client.TfsConnection.GetServiceInstance(Type serviceType, Object serviceInstance)
   at Microsoft.TeamFoundation.Client.TfsTeamProjectCollection.GetServiceInstance(Type serviceType, Object serviceInstance)
   at Microsoft.TeamFoundation.Client.TfsConnection.GetService(Type serviceType)
   at Microsoft.TeamFoundation.Client.TfsConnection.GetService[T]()
   at Microsoft.ALMRangers.PermissionsExtractionTool.Program.ExtractPermissionForUserName(IIdentityManagementService ims, String userName, Options options, String fileName, TfsTeamProjectCollection tfs) in C:\Projects\Extracting-effective-permissions-from-TFS-master\Source\PermissionsExtractionTool\PermissionsExtractionTool\Program.cs:line 143
   at Microsoft.ALMRangers.PermissionsExtractionTool.Program.Main(String[] args) in C:\Projects\Extracting-effective-permissions-from-TFS-master\Source\PermissionsExtractionTool\PermissionsExtractionTool\Program.cs:line 101

**Comment by jeffrey-opdam** [comment]
Closing issue, due too we deprecated this project.
